services:
  api:
    build: ./
    image: restapi
    container_name: restapi
    environment:
      - DB_URL=postgres://admin:pass@db:5432/tasksdb?sslmode=disable
      - PORT=:8080
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:16-alpine
    restart: always
    container_name: pgdb
    environment:
      - POSTGRES_DB=tasksdb
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=admin
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - PGDATA:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d tasksdb"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  
volumes:
  PGDATA: